### ISSUE TITLE
Change typos pre-commit hook

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#167]
https://github.com/sadikkuzu/squiral/blob/bf54989147c0253fa923adbc8ebe685bea4940b4/.pre-commit-config.yaml#L18-L21

https://github.com/crate-ci/typos/issues/390#issuecomment-2764488396

```
repos:
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.31.0
    hooks:
      - id: typos
```
