### ISSUE TITLE
squiral cli

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#33]
Use squiral from command line

**Comment by sadikkuzu** [comment]
`squiral/main.py`
```python
from sys import argv

import squiral.squiral as sq

def main_cli():
    sq.printout(sq.produce(int(argv[-1])))
```

`squiral/__init__.py`
```python
from .main import (
    main_cli,
)

 __all__ = [
    'produce',
    'printout',
    'main_cli',
 ]
```

`pyproject.toml`
```toml
[tool.poetry.scripts]
squiral = "squiral.main:main_cli"
```

---

```shell
$ pip install squiral
$ squiral 5
21 22 23 24 25
20  7  8  9 10
19  6  1  2 11
18  5  4  3 12
17 16 15 14 13
```
