### ISSUE TITLE
Add "reorder_python_imports" as a pre-commit hook

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#39]
https://github.com/asottile/reorder_python_imports#as-a-pre-commit-hook

```yaml
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
```

and then run 
```shell
poetry run pre-commit autoupdate && poetry run pre-commit run --all-files
```
