### ISSUE TITLE
Static type checking

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#63]
`.pre-commit-config.yaml`

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
```
