### ISSUE TITLE
Refactor lint&test github action

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/squiral#66]
1. [x] Remove pypy
2. [x] Add `3.11-dev`
3. [x] Add cache mechanism for pre-commit

```yaml
        python-version: ${{ matrix.python-version }}
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install dependencies
```
